### ISSUE TITLE
Format code with new rustfmt.toml

### ISSUE THREAD

**Issue by BORN2LOSE** [BORN2LOSE/amethyst#3]
```toml
merge_imports = true
reorder_imports = true
reorder_imported_names = true
reorder_imports_in_group = true
struct_field_align_threshold = 20
condense_wildcard_suffixes = true
format_strings = true
wrap_comments = true
where_single_line = true
use_field_init_shorthand = true
use_try_shorthand = true
```
